### ISSUE TITLE
Validate data.js using DangerJS

### ISSUE THREAD

**Issue by davidak** [wesbos/awesome-uses#999]
https://github.com/wesbos/awesome-uses/pull/998/checks
```
Run npx danger ci
You need to add GITHUB_TOKEN to your Danger action in the workflow:
  
    - name: Danger JS
      uses: danger/danger-js@X.Y.Z
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
The DANGER_GITHUB_API_TOKEN/DANGER_BITBUCKETSERVER_HOST/DANGER_GITLAB_API_TOKEN environmental variable is missing
Without an api token, danger will be unable to comment on a PR
Error:  Error: Cannot use authenticated API requests.
    at Object.getPlatformForEnv (/home/runner/work/awesome-uses/awesome-uses/node_modules/danger/distribution/platforms/platform.js:76:11)
    at Object.<anonymous> (/home/runner/work/awesome-uses/awesome-uses/node_modules/danger/distribution/commands/ci/runner.js:81:57)
    at step (/home/runner/work/awesome-uses/awesome-uses/node_modules/danger/distribution/commands/ci/runner.js:32:23)
    at Object.next (/home/runner/work/awesome-uses/awesome-uses/node_modules/danger/distribution/commands/ci/runner.js:13:53)
    at fulfilled (/home/runner/work/awesome-uses/awesome-uses/node_modules/danger/distribution/commands/ci/runner.js:4:58)
Error: Process completed with exit code 1.
```

**Comment by Joshua-rose** [comment]
Received the same with #1000

**Comment by jorgeruvalcaba** [comment]
I'm getting the same in #1004

**Comment by HugoDF** [comment]
Yeah this is one for @wesbos he needs to give dangerJS the right permissions

**Comment by rohit-gohri** [comment]
I mentioned this in the original issue https://github.com/wesbos/awesome-uses/issues/478#issuecomment-623157116 for automating checks. But forgot to mention in the PR (#796) that a secret `DANGER_GITHUB_API_TOKEN` will need to be added to the project and now it's merged without access to the repo 🙈.

**Comment by itsmanojb** [comment]
Still failing. 

![Screenshot from 2020-10-28 02-25-42](https://user-images.githubusercontent.com/11155266/97361143-25fe9f80-18c5-11eb-87dd-1b0c9c0cdd2e.png)
